[viewer]
    Title = "个人博客"
    Description = "基于golang原生http库博客-基于模板"
    Logo = "/resource/images/logo.png"
    Navigation = ["首页","/", "归档","/pigeonhole", "关于","/about"]
    Bilibili = "https://space.bilibili.com/473844125"
    Zhihu = "https://www.zhihu.com/people/ma-shen-zhi-lu"
    Avatar = "http://ryykyck5k.hd-bkt.clouddn.com/workbench/imgs/9EpIpnYr7KZ2GpiVNcno--1--h41fy.jpg"
    UserName = "高彪栗"
    UserDesc = "同济大学2022级硕士"
[system]
    
    CdnURL = "/resource"
    QiniuAccessKey = "u2aoNVS0_ha4DLVJ6vEWYE5tFJ12gAS3uGQkWH8B"
    QiniuSecretKey = "gigDWjd1cW4eyAA5NubSXVbLKwxmV_WnDgMtnV-9"
    bucket="gaobiaoli-blog"
    Valine = true
    ValineAppid = "M5X0uEI1ypfIFK6oMesPdb3b-gzGzoHsz"
    ValineAppkey = "xjCp4xTmKxw93um8u4wmYlb5"
    ValineServerURL = "https://m5x0uei1.lc-cn-n1-shared.com"